---
title: "R Notebook"
output: html_notebook
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
rm(list=ls())

library(vegan)
library(ggarchery)
library(data.table)
library(ggpubr)
library(ggpmisc)
library(scales)
library(readxl)
library(reshape2)
library(dplyr)
library(tidyr)
library(stringr)
library(writexl)
library(ggpubr)
library(gridExtra)
library(grid)
library(RColorBrewer)
library(xlsx)
library(tibble)
library(umap)
library(ComplexHeatmap)
library(ggplot2)
library(circlize)
library(viridis)
library(extrafont)
library(ggplot2)
library(showtext)
font_add_google("Gafata")
showtext_auto()
```

```{r variables}
file_path = 'C:/Users/morts/Documents/TAU/Manifold_Project/Data/SPECIFIC_PAPERS/'

file_name = paste0(file_path, 'Ravel_et_al.2013/Both_hiseq_454/IVC0_high_12_15/ps_results_IV-C0_high_18122022.xlsx')#'Serrano_Ravel2013_Ravel2011/IVC0_PCA_20_20_29012023/ps_res_29012023.xlsx') #'Serrano_et_al.2019/noDuplicatedID/DADA2_results/SILVA/PAGA_Results/ps_results_IV-A0_13072022.xlsx')

sheet_abun = 'abundance'
sheet_meta = 'meta'
sheet_umap = 'umap'
sheet_pcoa = 'pcoa'

save_path = paste0(file_path, 'Serrano_Ravel2013_Ravel2011/IVC0_PCA_20_20_29012023/figures/opening_chart/')

date = '01012023'
```

```{r}
community_colors = c('I-A' = '#9d0208', 'I-B' = '#dc2f02', 'II' = '#FFD60A', 'III-A' = '#e85d04','III-B' = '#faa307','IV-A' = '#22577a', 'IV-B' = '#5390D9', 'IV-C0' = '#2E214F', 'IV-C1' = '#63479B','IV-C2' = '#8962C7', 'IV-C3' = '#AB7DDA', 'IV-C4' = '#DEC9E9', 'V' = '#E2D6B8')

db_colors = c('temp_pyro' = '#006d77', 'temp_hiseq' = '#83c5be', 'cros_I' = '#ffddd2', 'cros_II' = '#d95e30')

coltypes_vector = c("text", "text", "numeric", "text", "text", "text", "numeric", "numeric", "numeric", 
                 "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "text",
                 "text", "numeric", "numeric", "text", "text", "numeric", "numeric", "numeric")
```

```{r, fig.height = 2, fig.width = 3}
set.seed(42)
n = 700
fa1.right <- sort(runif(n, min = 5, max = 10))
fa1.left <- sort(runif(n, min = 2.5, max = 5))
fa1.right.down <- sort(runif(n, min = , max = 5))

fa2.right <- sort(rnorm(1:n, mean = 80, sd = 10), decreasing = FALSE)
fa2.left <- sort(rnorm(1:n, mean = 38, sd = 8), decreasing = FALSE)
fa2.right.down <- sort(rnorm(1:n, mean = 80, sd = 10), decreasing = TRUE)

ps.right <- sort(runif(n, min = 0, max = 1), decreasing = FALSE)
ps.left <- sort(runif(n, min = 0, max = 1), decreasing = TRUE)
ps.right.down <- sort(runif(n, min = 0, max = 1), decreasing = TRUE)

df = data.frame(fa1 = c(fa1.right, fa1.left, fa1.right.down), fa2 = c(fa2.right, fa2.left, fa2.right.down), ps = c(ps.right, ps.left, ps.right.down))
df = df %>% 
     mutate(root = case_when(ps <= 0.005 ~ "root",
                                       ps > 0.005  ~ "reg")) %>%
     mutate(ps = ifelse(root == "root", NA, ps))
  
ggplot(data = df) +
  coord_flip() +
  geom_jitter(aes(x = fa1, y = fa2, color = ps), width = 0.5, height = 1)
```

# Regular

```{r}
r = ggplot(data = df) +
    geom_point(aes(x = fa1, y = fa2), pch = 21, size = 2, stroke = 0.4, color = '#0F0F19', fill = 'slategray4', alpha = 0.8, position = position_jitter(seed = 42, width = 0.5, height = 0.5)) +
    coord_flip() +
    theme_bw() +
    theme(axis.title = element_blank(),
          axis.text = element_blank())
print(r)
```

# White

```{r}
r = ggplot(data = df) +
    geom_point(aes(x = fa1, y = fa2), pch = 21, size = 2, stroke = 0, color = '#C5C8DD', fill = '#C5C8DD', alpha = 1, position = position_jitter(seed = 42, width = 0.5, height = 0.5)) +
    coord_flip() +
    theme_bw() +
    theme(axis.title = element_blank(),
          axis.text = element_blank())
print(r)
```

```{r, fig.height=5, fig.width=6}
cols_magma = c('#F6F7E0', '#fcfdbf', '#fde2a3', '#fec68a', '#fec488', '#fec488', '#fea772', '#fc8961', '#fc8961', '#f56b5c', '#f56b5c',
               '#e75263', '#D54875', '#D54875', '#d0416f', '#b73779', '#9c2e7f', '#832681', '#6a1c81', 
               '#51127c', '#36106b', '#1d1147', '#0a0822', '#000004')
col_fun = colorRamp2(c(0, 0.25, 0.5, 0.75, 1), c("#DC143C", "#FFA07A", "#FFEFD5", "#87CEFA", "#6495ED"))

p = ggplot() +
    geom_point(data = subset(df, root == 'reg'), aes(x = fa1, y = fa2, fill = ps),
               pch = 21, size = 1, stroke = 0.4, color = '#0F0F19', alpha = 0.7,
               position = position_jitter(seed = 42, width = 0.5, height = 0.5)) +
    geom_point(data = subset(df, root == 'root'), aes(x = fa1, y = fa2),
               pch = 21, size = 3, stroke = 0.4, color = '#0F0F19', alpha = 0.98, fill = '#23232E',
               position = position_jitter(seed = 42, width = 0.5, height = 0.5)) +
    # geom_point(data = n_umap, aes(x = fa1, y = fa2, fill = ps),
    #            pch = 21, size = 1.3, stroke = 0.4, color = '#0F0F19', alpha = 0.7,
    #            position = position_jitter(seed = 42, width = 3, height = 3)) +
    theme_bw(base_family = 'Gafata') +
    coord_flip() +
    labs(title = '', x = '', y = '', fill = 'Pseudo-time') + 
    # scale_fill_gradientn(colors = c('#fcfdbf', '#feb078', '#f1605d', '#b73779', '#721f81', '#2c115f'), 
    #                     breaks = c(0, 0.25, 0.5, 0.75, 1)) +
    scale_fill_gradientn(colors = rev(c('#F8F8D6', '#fcfdbf','#fc8961','#b73779', '#51127c', '#000004')), #rev(cols_magma),
                        values = rev(c(0, 0.25, 0.5, 0.75, 0.9, 1)), #c(0, 0.25, 0.5, 0.75, 1), 
                        'Pseudo-time') +
                        # na.value = '#23232E') +
    theme(text = element_text(size = 30),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          axis.title = element_blank(),
          plot.title = element_text(hjust = 0.5),
          legend.position = "bottom",
          legend.text = element_text(angle = 45),
          legend.margin = margin(0,0,0,0),
          legend.box.margin = margin(-10,0,0,0),
          legend.spacing.y = unit(0.1, 'in')) +
  
  guides(fill = guide_colourbar(barwidth = 10, barheight = 1, frame.colour = '#23232E', ticks.colour = 'black', reverse = FALSE,
                                title.hjust = 1.5, title.vjust = 0.8, label.hjust = 0.8),
         color = guide_legend(ncol = 2))
print(p)
```








