```{r}
rm(list=ls())

library(vegan)
library(data.table)
library(ggpubr)
library(scales)
library(readxl)
library(reshape2)
library(dplyr)
library(tidyr)
library(writexl)
library(ggpubr)
library(RColorBrewer)
library(xlsx)
library(tibble)
# library(ComplexHeatmap)
library(umap)
```

*** Variables ***
```{r}
all_file_path = 'C:/Users/morts/Documents/TAU/BV_project/Pseudo_time_analysis/Ravel11/PCA_noTransitions_10012022/'
file_name = 'ps_results_10012022.xlsx'
sheet_name_data = 'abundance_pseudo'
sheet_name_metadata = 'metadata_pseudo'
sheet_name_graph = 'graph_pseudo'


```

*** Load data ***
```{r}
get_df = function(file_path, sheet_name){
  filename = paste(all_file_path, file_path, sep = '')
  raw_df = read_excel(filename, sheet = sheet_name)
  
  df = data.frame(column_to_rownames(raw_df, var = "sampleID"))
  
  return(df)
}
```

```{r}
data_df = get_df(file_name, sheet_name_data)
names(data_df) <- gsub(x = names(data_df), pattern = "\\..", replacement = "_")
meta_df = get_df(file_name, sheet_name_metadata)
print(head(data_df))
print((meta_df))
```
*** UMAP for Ravel ***
```{r}
cros_umap = umap(data_df, n_neighbors = 8)
```

```{r}
cros_umap
class(cros_umap)
class(cros_umap$layout)
head(cros_umap$layout, 5)

```

```{r}
print(class(cros_umap$data))
# print(head(cros_umap$data, 3))
```

```{r}
print(class(cros_umap$knn$indexes))
print(head(cros_umap$knn$indexes, 3))
print(dim(cros_umap$knn$indexes))
```
```{r}
print(max(cros_umap$knn$indexes))
print(min(cros_umap$knn$indexes))
```


```{r}
print(head(cros_umap$knn$distances, 3))
print(dim(cros_umap$knn$distances))
```

```{r}
cros_umap$config
```


```{r}
get_ggplot = function(umap_mat, orig_df){
  umap_df = as.data.frame(umap_mat)
  colnames(umap_df) = c('umap1', 'umap2')
  fig = ggplot(umap_df, aes(x = umap1, y = umap2)) + geom_point()
  
  return(fig)
}
```

```{r}
cros_umap_df = get_ggplot(cros_umap$layout, data_df)
print(cros_umap_df)
```

*** Tutorial UMAP Projection ***
```{r}
iris.data = iris[, grep("Sepal|Petal", colnames(iris))]
iris.labels = iris[, "Species"]
iris.umap = umap(iris.data)
iris.umap
head(iris.umap$layout, 3)
```

```{r}
iris_umap_df = as.data.frame(iris.umap$layout)
colnames(iris_umap_df) = c('umap1', 'umap2')
ggplot(iris_umap_df, aes(x = umap1, y = umap2)) + geom_point()
```
```{r}
iris.wnoise = iris.data + matrix(rnorm(150*40, 0, 0.1), ncol=4)
colnames(iris.wnoise) = colnames(iris.data)
iris.wnoise.umap = predict(iris.umap, iris.wnoise)
head(iris.wnoise.umap, 3)

```

```{r}
iris_umap_df2 = as.data.frame(iris.wnoise.umap)
colnames(iris_umap_df2) = c('umap1', 'umap2')
ggplot(iris_umap_df2, aes(x = umap1, y = umap2)) + geom_point()
```


```{r}


```








